fitfuel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('food.urls')),
    path('users/', include('users.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

food/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('menu', views.menu, name='menu'),
    path('contact', views.contact, name='contact'),
    path('checkout/update-cart', views.update_session_cart, name='update_session_cart'),
    path('checkout', views.checkout_page, name='checkout_page'),
    path('api/checkout-session', views.create_checkout_session, name='api_checkout_session'),
    path('success', views.payment_success_view, name='success'),
    path('failed', views.payment_failed_view, name='failed'),
    path('stripe-webhook/', views.stripe_webhook, name='stripe_webhook'),
]

food/models.py
from django.db import models
from django.core.validators import MinValueValidator
import math 


# Represents a category for menu items (Main Course, Drinks etc...)
class MenuItemCategory(models.Model):
    name = models.CharField(max_length=100, unique=True, help_text='Category of a specific Menu Item')
    index = models.IntegerField(default=0, help_text='Which category shows up first')
    image_url = models.URLField(max_length=500, blank=True, null=True, help_text="URL of the image for this category")
    
    class Meta:
        verbose_name = 'Menu Item Category'
        verbose_name_plural = 'Menu Item Categories'
        ordering = ['index']

    def __str__(self):
        return self.name


# Represents a singular instance of a menu item
class MenuItem(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, help_text='A brief description of the menu item')
    image_url = models.URLField(max_length=500, blank=True, null=True, help_text="URL of the image for this menu item")
    calories = models.IntegerField(default=0, help_text='Calories per 100g')
    carbs = models.IntegerField(default=0, help_text='Carbohydrates per 100g')
    protein = models.IntegerField(default=0, help_text='Protein per 100g')
    fats = models.IntegerField(default=0, help_text='Fats per 100g')
    category = models.ForeignKey(
        MenuItemCategory, on_delete=models.SET_NULL, null=True, 
        blank=True, help_text='The category this menu item belongs to'
    )
    
    class Meta:
        verbose_name = 'Menu Item'
        verbose_name_plural = 'Menu Items'
    
    def __str__(self):
        return f"{self.name} ({self.category.name if self.category else 'Uncategorized'})"


# Represents a specific portion size for a MenuItem, with its own price and amount.
class MenuItemPortion(models.Model):
    menu_item = models.ForeignKey(MenuItem, related_name='portions', on_delete=models.CASCADE, help_text="The menu item this portion belongs to")
    name = models.CharField(max_length=100, help_text="Name of the portion ('Small', 'Regular', etc...)")
    amount_in_grams_ml = models.IntegerField(default=100, help_text="Amount for this portion in grams or milliliters")
    price = models.FloatField(default=10, validators=[MinValueValidator(0.0, message='Price cannot be negative.')])
    discount_percent = models.FloatField(default=0, validators=[MinValueValidator(0.0, message='Discount cannot be negative.')])

    class Meta:
        verbose_name = "Menu Item Portion"
        verbose_name_plural = "Menu Item Portions"
        # A menu item cannot have two portions with the same name
        unique_together = ('menu_item', 'name') 

    def __str__(self):
        return f"{self.menu_item.name} - {self.name} ({self.amount_in_grams_ml}g/ml) - ${self.price}"
    
    def calculate_macros_for_portion(self):
        scale_factor = self.amount_in_grams_ml / 100

        portion_calories = math.ceil(self.menu_item.calories * scale_factor)
        portion_protein = math.ceil(self.menu_item.protein * scale_factor)
        portion_carbs = math.ceil(self.menu_item.carbs * scale_factor)
        portion_fats = math.ceil(self.menu_item.fats * scale_factor)

        return {
            'calories': portion_calories,
            'protein': portion_protein,
            'carbs': portion_carbs,
            'fats': portion_fats
        }
        
    def get_discount_price(self):
        return round(self.price - self.price * (self.discount_percent / 100), 1)
        
    def get_final_price(self):
        if self.discount_percent and self.discount_percent > 0:
            discount_amount = self.price * (self.discount_percent / 100)
            return round(self.price - discount_amount, 2)
        return round(self.price, 2)
        
        
# Orders are created after checkout to gather all items purchased and the customer information
class Order(models.Model):
    stripe_checkout_session_id = models.CharField(max_length=255, unique=True, null=True, blank=True)
    customer_email = models.EmailField()
    customer_phone = models.CharField(max_length=200, blank=True)
    customer_address = models.CharField(max_length=200, blank=True)
    customer_zipcode = models.CharField(max_length=200, blank=True)
    
    total_price = models.FloatField(default=0.0)

    order_date = models.DateTimeField(auto_now_add=True)    
    has_paid = models.BooleanField(default=False)
    is_shipped = models.BooleanField(default=False)
    
    # This JSON field is structured like this:
    # 'item_name': Name of the item,
    # 'portion_id': ID of the item portion - used when we need to display info on the Frontend (e.g. past orders),
    # 'portion_name': Name of the portion - display purposes,
    # 'quantity': How much of any particular portion has been bought,
    # 'total_price': Sum of all portions, quantities and prices together, this is how much the customer needs to pay
    order_items = models.JSONField(default=list, blank=True)
    
    def __str__(self):
        return f"Order #{self.id} - {self.customer_email}"
    
    def get_order_macros(self):
        macros = {
            'carbs': 0,
            'protein': 0,
            'fats': 0
        }
        
        for item in self.order_items:
            portion = MenuItemPortion.objects.get(id=item['portion_id'])
            portion_macros = portion.calculate_macros_for_portion()
            
            macros['carbs'] += portion_macros['carbs']
            macros['protein'] += portion_macros['protein']
            macros['fats'] += portion_macros['fats']
            
        return macros
            
            
            

food/forms.py
from django import forms


class CheckoutForm(forms.Form):    
    email = forms.EmailField(label='Email address')
    phone = forms.CharField(label='Phone')
    address = forms.CharField(label='Address')
    city = forms.CharField(label='City')
    zip_code = forms.CharField(label='Zip Code')

food/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse  
from django.conf import settings
from django.urls import reverse
from django.db import transaction
from .models import MenuItem, MenuItemCategory, MenuItemPortion, Order
from .forms import CheckoutForm
import json, stripe


def index(request):
    return render(request, 'food/index.html')


def menu(request):
    menu_items = MenuItem.objects.all()
    menu_categories = MenuItemCategory.objects.all()
    return render(request, 'food/menu.html', {'menu_items': menu_items, 'menu_categories': menu_categories})


def contact(request):
    return render(request, 'food/contact.html')


def update_session_cart(request):
    try:
        raw_body = request.body.decode('utf-8')
        data = json.loads(raw_body)
        cart_from_js = data.get('cart', {})

        valid_cart = {}
        
        if cart_from_js:
            for portion_id, data_list in cart_from_js.items():
                try:
                    valid_cart[portion_id] = int(data_list[1])

                except (ValueError, TypeError, IndexError) as e:
                    print(f"Invalid item conversion from JS, Portion ID String:'{portion_id}', Data:'{data_list}'. Error: {e}")
                    continue

        request.session['cart'] = valid_cart
        request.session.modified = True

        return JsonResponse({'status': 'success', 'message': 'Cart session updated.'})
    except Exception as e:
        print(f"Error occurred in update_session_cart(): {e}")
        
        import traceback
        traceback.print_exc()
        return JsonResponse({'status': 'error', 'message': f'Server error: {str(e)}'}, status=500)


def checkout_page(request):
    # This will be used in the checkout.html for display purposes
    cart_context = []
    total_cart_price = 0

    if 'cart' in request.session:
        cart = request.session['cart']
        
        # Get all items from the Javascript cart and use it for our context 
        for portion_id, quantity in cart.items():
            try:
                portion = MenuItemPortion.objects.get(id=portion_id)
                final_price = portion.get_final_price()
                item_total = final_price * quantity
                image_url = portion.menu_item.image_url

                cart_context.append({
                    'menu_item_name': portion.menu_item.name,
                    'portion_name': portion.name,
                    'quantity': quantity,
                    'price_per_item': final_price,
                    'item_total': item_total,
                    'image_url': image_url,
                })
                total_cart_price += item_total

            except MenuItemPortion.DoesNotExist:
                print(f"Portion with ID {portion_id} not found in checkout_page().")
                continue
    
    stripe_publishable_key = settings.STRIPE_PUBLISHABLE_KEY
    
    if request.user.is_authenticated:
        initial_data = {
            'email': request.user.email,
            'phone': getattr(request.user, 'phone', ''), 
            'address': getattr(request.user, 'address', ''),
            'city': getattr(request.user, 'city', ''),
            'zip_code': getattr(request.user, 'zip_code', ''),
        }
        checkout_form = CheckoutForm(initial=initial_data)
    else:
        # For non-authenticated users, initialize an empty form
        checkout_form = CheckoutForm()
    
    return render(request, 'food/checkout.html', {
        'cart_items': cart_context, 
        'total_cart_price': total_cart_price,
        'stripe_publishable_key': stripe_publishable_key,
        'checkout_form': checkout_form
    })


def create_checkout_session(request):
    request_data = json.loads(request.body)
    
    # Make sure the user information from the form is correct before proceeding
    form = CheckoutForm(request_data)
    if not form.is_valid():
        return JsonResponse({'error': form.errors.as_json()}, status=400)
    
    user_email = form.cleaned_data['email']
    user_phone = form.cleaned_data['phone']
    user_address = form.cleaned_data['address']
    user_zipcode = form.cleaned_data['zip_code']

    current_cart = request.session.get('cart', {})
    line_items = []
    
    # Loop through the Javascript cart to generate information needed for Stripe
    for portion_id, quantity in current_cart.items():
        portion = MenuItemPortion.objects.get(id=int(portion_id))
        line_items.append({
            'price_data': {
                'currency': 'eur',
                'product_data': {
                    'name': f"{portion.menu_item.name} ({portion.name})",
                    'images': [portion.menu_item.image_url] if portion.menu_item.image_url else [],
                    # This metadata will be used for creating orders later
                    'metadata': {
                        'menu_item_name': portion.menu_item.name,
                        'portion_name': portion.name,
                        'portion_id': portion.id
                    }
                },
                'unit_amount': int(portion.get_final_price() * 100),
            },
            'quantity': quantity,
        }) 

    # Create the Stripe session for payment
    stripe.api_key = settings.STRIPE_SECRET_KEY  
    checkout_session = stripe.checkout.Session.create(
        customer_email= user_email,
        payment_method_types= ['card'],
        line_items= line_items,
        mode= 'payment',
        metadata={
            'customer_email': user_email,
            'customer_phone': user_phone,
            'customer_address': user_address,
            'customer_zipcode': user_zipcode,
        },
        success_url= request.build_absolute_uri(reverse('success')) +
        "?session_id={CHECKOUT_SESSION_ID}",
        cancel_url= request.build_absolute_uri(reverse('failed')),
    )
    
    return JsonResponse({'sessionId': checkout_session.id})
    
    
@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    event = None
    
    # Verify that the request came for Stripe - security purpose
    try:
        event = stripe.Webhook.construct_event(
            payload, 
            request.META.get('HTTP_STRIPE_SIGNATURE'), 
            settings.STRIPE_WEBHOOK_SECRET
        )
    except stripe.error.SignatureVerificationError as e:
        print(f'Request did not come from Stripe, or API_SECRET is wrong')
        return HttpResponse(status=400)
    except Exception as e:
        print(f'Exception caught when trying to verify Stripe request, error: {e}')
        return HttpResponse(status=500)

    if event['type'] == 'checkout.session.completed':
        # Checkout session object
        session = event['data']['object']

        # Prevention of duplicate orders in case of multiple webhooks at the same time
        try:
            with transaction.atomic():
                if Order.objects.filter(stripe_checkout_session_id=session.id).exists():
                    return HttpResponse(status=200)

                full_session = stripe.checkout.Session.retrieve(
                    session.id,
                    expand=['line_items']
                )
                
                # Retrieve the metadata that was passed during session creation
                customer_email = full_session.metadata.get('customer_email', '') 
                customer_phone = full_session.metadata.get('customer_phone', '')
                customer_address = full_session.metadata.get('customer_address', '')
                customer_zipcode = full_session.metadata.get('customer_zipcode', '')

                # Stripe has amount total in cents so we need to recalculate it here
                order_total = session.amount_total / 100 

                # This is to gain access to the product metadata
                full_session_items = stripe.checkout.Session.list_line_items(
                    session['id'], expand=['data.price.product']
                )

                # Get all line items from the checkout session and format them for the order
                processed_order_items = []
                for item in full_session_items:
                    product = item['price']['product']
                    
                    menu_item_name = product['metadata'].get('menu_item_name', '')
                    portion_name = product['metadata'].get('portion_name', '')
                    portion_id = product['metadata'].get('portion_id', '')
                    
                    # JSON Format for the Order
                    processed_order_items.append({
                        'item_name': menu_item_name,
                        'portion_id': portion_id,
                        'portion_name': portion_name,
                        'quantity': item.quantity,
                        'total_price': item.amount_total / 100,
                    })
                
                # Creating and saving the order
                order = Order.objects.create(
                    stripe_checkout_session_id=session.id,
                    customer_email=customer_email,
                    customer_phone=customer_phone,
                    customer_address=customer_address,
                    customer_zipcode=customer_zipcode,
                    total_price=order_total,
                    order_items=processed_order_items,
                    has_paid=True,
                )
                order.save()
                # TODO: Could add a confimation email here later
        except stripe.error.StripeError as e:
            print(f'Stripe API call error: {e}')
            return HttpResponse(status=400)
        except Exception as e:
            print(f'Exception error in stripe_webhook method: {e}')
            return HttpResponse(status=500)

    return HttpResponse(status=200)


def payment_success_view(request):

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--CSRF Token-->
    <meta name="csrf-token" content="{{ csrf_token }}">

    <!-- Bootstrap 5 CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- Custom Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Regular Straight -->
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/3.0.0/uicons-regular-straight/css/uicons-regular-straight.css'>
    <!-- Regular Rounded -->
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/3.0.0/uicons-regular-rounded/css/uicons-regular-rounded.css'>
    <!-- Brands -->
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/3.0.0/uicons-brands/css/uicons-brands.css'>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Funnel+Display:wght@300..800&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Funnel+Display:wght@300..800&family=Manrope:wght@200..800&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <!-- Bootstrap 5 JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    {% block content %}{% endblock %}

    <!-- JQuery -->    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</body>
</html>

food/templates/food/checkout.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %}FitFuel - Checkout{% endblock %}
{% block content %}
{% include 'food/header.html' %}

<div class="page-container decal-background">
    <div class="order straight-card">
        <div class="cart-list">
            {% for item in cart_items %}
            <div class="cart-list__item">
                <img src="{{ item.image_url }}" alt="" class="cart-list__item-image">
                <div class="cart-list__item-info">
                    <div class="cart-list__item-info-name">{{ item.menu_item_name }}</div>
                    <div class="cart-list__item-info-portion">
                        <div class="cart-list__item-info-portion-size">{{ item.portion_name }}</div>
                        <div class="cart-list__item-info-portion-quantity">x{{ item.quantity }}</div>
                    </div>
                </div>
                <div class="cart-list__item-price">{{ item.price_per_item }}€</div>
            </div>
            {% endfor %}
        </div>

        <div class="order__total">Total: {{ total_cart_price }}€</div>
    </div>
    <form class="straight-card card-form info-form" method="POST" action="">
        <h1 class="card-title">Checkout Form</h1>
        {% csrf_token %}
        <div class="card-form__form">
            <div class="card-form__form-section">
                <label>Email</label>
                <div id="id_email" class="card-form__form-section-input">{{ checkout_form.email }}</div> 
            </div>
            <div class="card-form__form-section">
                <label>Phone</label>
                <div id="id_phone" class="card-form__form-section-input">{{ checkout_form.phone }}</div> 
            </div>
            <div class="card-form__form-section">
                <label>City</label>
                <div id="id_city" class="card-form__form-section-input">{{ checkout_form.city }}</div> 
            </div>
            <div class="card-form__form-section">
                <label>Address</label>
                <div id="id_address" class="card-form__form-section-input">{{ checkout_form.address }}</div> 
            </div>
            <div class="card-form__form-section">
                <label>Zipcode</label>
                <div id="id_zipcode" class="card-form__form-section-input">{{ checkout_form.zip_code }}</div> 
            </div>
            <div id="form-errors"></div>
        </div>

        <button id="main-checkout-button" class="main-button" type="submit">Checkout</button>
    </form>
</div>

{% include 'food/footer.html' %}

<!--Stripe JS CDN-->
<script src="https://js.stripe.com/basil/stripe.js"></script>

<script type="text/javascript">

var stripe = Stripe('{{ stripe_publishable_key }}');
var checkoutForm = document.getElementById('checkoutForm');
var checkoutButton = document.getElementById('main-checkout-button');
var formErrorsDiv = document.getElementById('form-errors');

checkoutButton.addEventListener('click', function() {
    event.preventDefault();
    formErrorsDiv.innerHTML = ''; 

    var emailInput = document.getElementById('id_email').querySelector('input');
    var phoneInput = document.getElementById('id_phone').querySelector('input');
    var addressInput = document.getElementById('id_address').querySelector('input');
    var cityInput = document.getElementById('id_city').querySelector('input');
    var zipcodeInput = document.getElementById('id_zipcode').querySelector('input');

    var formData = {
        email: emailInput.value.trim(),
        phone: phoneInput.value.trim(),
        address: addressInput.value.trim(),
        city: cityInput.value.trim(),
        zip_code: zipcodeInput.value.trim()
    };

    // --- Client-side Validation ---
    var errors = [];

    if (!formData.email || !formData.phone || !formData.city || !formData.address || !formData.zip_code) {
        errors.push('All fields are required.');
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
        errors.push('Please enter a valid email address.');
    }

    if (errors.length > 0) {
        formErrorsDiv.innerHTML = errors.join(' ');
        return;
    }

    checkoutButton.disabled = true;
    checkoutButton.textContent = 'Processing';

    // CSRF Token is in the base.html meta tag
    const csrftoken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');

    fetch("{% url 'api_checkout_session' %}", {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': csrftoken
        },
        body: JSON.stringify(formData)
    }).then(function(response) {
        return response.json();
    }).then(function(session) {
        if (session.error) {
            alert('Error creating checkout session: ' + session.error);
            
            checkoutButton.disabled = false;
            checkoutButton.textContent = 'Checkout';
            return;
        }
        return stripe.redirectToCheckout({sessionId: session.sessionId});
    })
})

</script>

{% endblock %}

food/templates/food/contact.html
{% extends 'food/base.html' %}
{% block title %}FitFuel - Contact{% endblock %}
{% block content %}
{% include 'food/header.html' %}

<div class="viewport-height-container">
    <div class="straight-card contact">
        <h1 class="card-title">Developer Contact</h1>
        <div class="contact-info">
            <div class="contact-info__section">
                <div class="contact-info__section-title">LinkedIn</div>
                <div class="contact-info__section-description">I am active on LinkedIn, visit my profile by going <span><a href="https://www.linkedin.com/in/krsmanovic-stefan/">here</a></span> and send me a connect. You can view my experience, past projects and skills in detail on my profile page.</div>
            </div>
            <div class="contact-info__section">
                <div class="contact-info__section-title">Github</div>
                <div class="contact-info__section-description">
                    For a detail look into how all of this was coded, as well as a complete feature breakdown, stop by my github and checkout the repo <span><a href="https://github.com/Krsmanovic-S/fit-fuel">here</a></span>.
                </div>
            </div>
            <div class="contact-info__section">
                <div class="contact-info__section-title">Email</div>
                <div class="contact-info__section-description">If you have any questions feel free to contact me over email if that is what you prefer. You can send your emails to <span class="email">krsmanovic1998@gmail.com</span> and I'll respond as soon as I can.</div>
            </div>
        </div>
    </div>
</div>

{% include 'food/footer.html' %}
{% endblock %}

food/templates/food/footer.html
{% extends 'food/base.html' %}
{% load static %}
{% block content %}
<footer class="footer">

    <div class="copyright-text">© 2025 Stefan K.</div>

    <img class="logo-img" src="{% static 'img/logo.png' %}" alt="Fit Fuel Logo">

    <div class="icon-container">
        <a href="https://www.linkedin.com/in/krsmanovic-stefan/" class="icon-link">
            <i class="fi fi-brands-linkedin"></i>
        </a>
        <a href="https://github.com/Krsmanovic-S" class="icon-link">
            <i class="fi fi-brands-github"></i>
        </a>
        <a href="https://t.me/krsmanovics" class="icon-link">
            <i class="fi fi-brands-telegram"></i>
        </a>
    </div>
</footer>
{% endblock %}

food/templates/food/menu.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %}FitFuel - Menu{% endblock %}
{% block content %}
{% include 'food/header.html' %}

<div class="menu-container">
    {% for category in menu_categories %}
        <div class="category-container">
            <div class="category-container__title">{{ category.name }}</div>

            <div class="category-container__decal">
                <div class="horizontal-lines">
                    <hr class="line">
                    <hr class="line">
                </div>

                <div class="category_badge">
                    <img src="{% static 'categories/frame.png' %}" alt="Category Badge Frame" class="category_badge__frame">
                    <img src="{{ category.image_url }}" alt="Category Icon" class="category_badge__category-icon">
                </div>

                <div class="horizontal-lines">
                    <hr class="line">
                    <hr class="line">
                </div>
            </div>
        </div>

        <div class="menu-item-grid">
            {% for item in menu_items %}
                {% if item.category.id == category.id %}
                <div class="item-container round-card">

                    <div class="item-container__item-image">
                        <img src="{{ item.image_url }}" alt="Food Item Image" class="item-image">
                    </div>

                    <div class="item-container__title">{{ item.name }}</div>

                    <div class="item-container__macros">
                        <div class="item-container__macros-carbs custom-pill" data-type="carbs">Carbs: 35g</div>
                        <div class="item-container__macros-protein custom-pill" data-type="protein">Protein: 20g</div>
                        <div class="item-container__macros-fats custom-pill" data-type="fats">Fats: 15g</div>
                        <div class="item-container__macros-calories custom-pill" data-type="calories">Kcal: 380</div>
                    </div>

                    <div class="item-container__item-description">{{ item.description }}</div>

                    <form class="item-container__portion-container">
                        {% for portion in item.portions.all %}
                            {% with calculated_macros=portion.calculate_macros_for_portion %}
                            <div class="item-container__portion-container-option">
                                <input type="radio" id="portion-{{ portion.id }}" name="selected_portion" 
                                       value="{{ portion.id }}" {% if forloop.first %}checked{% endif %}
                                       data-carbs="{{ calculated_macros.carbs }}" data-proteins="{{ calculated_macros.protein }}"
                                       data-fats="{{ calculated_macros.fats }}" data-calories="{{ calculated_macros.calories }}">
                                <label for="portion-{{ portion.id }}">
                                    <span class="item-container__portion-container-option__name">{{ portion.name }}</span>
                                    <span class="item-container__portion-container-option__price">
                                        {{ portion.price }}€
                                        {% if portion.discount_percent %}
                                        {% with discount_value=portion.get_discount_price %}
                                        <div class="item-container__portion-container-option__price-discount">{{ discount_value }}€</div>
                                        {% endwith %}
                                        {% endif %}
                                    </span>
                                </label>
                            </div>
                            {% endwith %}
                        {% endfor %}
                    </form>

                    <div class="item-container__cart-button">
                        <a id="{{ item.id }}" href="#" data-image="{{ item.image_url }}" data-name="{{ item.name }}">Add to Cart</a>
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        </div>
    {% endfor %}
</div>

{% include 'food/footer.html' %}
{% endblock %}